#ifndef LADX_CONSTANTS_MEMORY_H
#define LADX_CONSTANTS_MEMORY_H

#include "common.h"

/* WRAM Sections */
#define wram0Section            0xC000
#define wIsFileSelectionArrowShifted 0xD000
#define wAudioSection           0xD300
#define wDrawCommandsSection    0xD600
#define wStackTop               0xDFFF

/* WRAM Gameplay Variables */
#define wMusicTrackTiming       0xC10B
#define wShouldGetLostInMysteriousWoods 0xC10C
#define wEntityTilesSpriteslotIndexB 0xC10D
#define wNeedsUpdatingEntityTilesB 0xC10E
#define wLinkMotionState        0xC11C
#define wIsUsingSpinAttack      0xC121
#define wSwordCharge            0xC122
#define wActiveEntityIndex      0xC123
#define wRoomTransitionState    0xC124
#define wRoomTransitionDirection 0xC125
#define wRandomSeed             0xC13D
#define wC140                   0xC140
#define wC141                   0xC141
#define wC142                   0xC142
#define wC143                   0xC143
#define wIsRunningWithPegasusBoots 0xC14A
#define wPegasusBootsChargeMeter 0xC14B
#define wTransitionSequenceCounter 0xC16B
#define wC167                   0xC167
#define wC16C                   0xC16C
#define wC1A2                        0xC1A2
#define wTimeToNextLowHealthSFX  0xC110
#define wIsOnLowHeath            0xC163
#define wC3CE                    0xC3CE
#define wConveyorBeltsCount          0xC1A5
#define wObjectAffectingBGPalette    0xC3CB
#define wC3CD                        0xC3CD
#define wC3CF                        0xC3CF
#define wC50E                        0xC50E
#define wRoomSwitchableObject        0xD6FA
#define wDoorsOpeningOrClosing       0xC188
#define wDoorEvent                   0xC189
#define wShutterDoorsMask            0xC18A
#define wC183                         0xC183
#define wShutterDoorsMask2           0xC18B
#define wEnqueueDoorsOpening         0xC18C
#define wEnqueueDoorsClosing         0xC18D
#define wRoomEvent                   0xC18E
#define wRoomEventEffectExecuted 0xC18F
#define wShutterDoorEventExecuted     0xC190
#define wLoadedEntitySpritesheets 0xC193
#define wEntityTilesSpriteslotIndexA 0xC197
#define wC19C                   0xC19C
#define wC19D                   0xC19D
#define wBGOriginHigh                 0xC12E
#define wBGOriginLow                  0xC12F
#define wNameIndex                    0xC108
#define wDialogIndexHi                0xC112
#define wDialogCooldown               0xC134
#define wDialogCharacterIndexHi       0xC164
#define wDialogOpenCloseAnimationFrame 0xC16F
#define wDialogCharacterIndex         0xC170
#define wDialogNextCharPosition       0xC171
#define wDialogScrollDelay            0xC172
#define wDialogIndex                  0xC173
#define wDialogAskSelectionIndex      0xC177
#define wC175                         0xC175
#define wC176                         0xC176
#define wDialogIsWaitingForButtonPress 0xC1CC
#define wDialogNextChar               0xC3C3
#define wIsMarinSinging               0xC3C8
#define wName                         0xDB4F
#define wIsThief                      0xDB6E
#define wLinkAnimationFrame           0xC198
#define wDialogState                  0xC19F
#define wDialogInteractionLocked      0xC1AB
#define wBGPaletteEffectAddress       0xC3CC
#define wDialogSFX                    0xC5AB
#define wC168                         0xC168
#define wC1CF                         0xC1CF
#define wDoorXPositions              0xC1D0
#define wDoorYPositions              0xC1E0
#define wDoorPositions               0xC1F0
#define wMusicTrackToPlay       0xD368
#define w2_D16A                 0xD16A
#define wWarp0MapCategory       0xD401
#define wWarpStructs            0xD401
#define wWarpPositions          0xD416
#define wWarp0PositionTileIndex 0xD416
#define wD460                   0xD460
#define wD464                   0xD464
#define wD474                   0xD474
#define wD477                   0xD477
#define wD478                   0xD478
#define wD47F                   0xD47F
#define wD500                   0xD500
#define wDrawCommand            0xD601
#define wOverworldRoomStatus    0xD800
#define wIndoorARoomStatus           0xD900
#define wIndoorBRoomStatus           0xDA00
#define wTradeSequenceItem           0xDB0E
#define wHasStolenFromShop           0xDB46
#define wTarinFlag                   0xDB48
#define wHasInstrument3              0xDB67
#define wIsBowWowFollowingLink       0xDB56
#define wIsMarinFollowingLink        0xDB73
#define wIsMarinInAnimalVillage      0xDB74
#define wKillCount                   0xDBB5
#define wKillOrder                   0xDBB6
#define wTorchesCount                0xDBC9
#define wColorDungeonRoomStatus      0xDDE0
#define wGameplayType           0xDB95
#define wGameplaySubtype        0xDB96
#define wIsIndoor               0xDBA5
#define wCurrentBank            0xDBAF
#define wDrawCommandsVRAM1Size  0xDC90
#define wDrawCommandVRAM1       0xDC91
#define wAnimatedScrollingTilesStorage 0xDCC0
#define wDDD8                   0xDDD8
#define wPaletteDataFlags       0xDDD1
#define wPaletteUnknownE        0xDDD5
#define wFarcallBank            0xDE01
#define wFarcallAdressHigh      0xDE02
#define wFarcallAdressLow       0xDE03
#define wFarcallReturnBank      0xDE04

/* Followers in WRAM */
#define wIsBowWowFollowingLink  0xDB56
#define wIsMarinFollowingLink   0xDB73
#define wIsGhostFollowingLink   0xDB79
#define wIsRoosterFollowingLink 0xDB7B
#define BOW_WOW_FOLLOWING       0x01

/* Room Objects in WRAM */
#define wRoomObjectsArea             0xD700
#define wRoomObjects                 0xD711
#define OBJECTS_PER_ROW              10

/* WRAM Entity Tables */
#define wOAMBuffer                            0xC000
#define wDynamicOAMBuffer                     0xC030
#define wScreenShakeHorizontal                0xC155
#define wEntitiesPosXSignTable                0xC220
#define wEntitiesPosYSignTable                0xC230
#define wEntitiesPosZSignTable                0xC340
#define wEntitiesPhysicsFlagsTable            0xC340
#define wEntitiesInertiaTable                 0xC3D0
#define wEntitiesPosXTable                    0xC200
#define wEntitiesPosYTable                    0xC210
#define wEntitiesPosZTable                    0xC310
#define wEntitiesSpeedXTable                  0xC240
#define wEntitiesSpeedYTable                  0xC250
#define wEntitiesSpeedZTable                  0xC320
#define wEntitiesSpeedXAccTable               0xC260
#define wEntitiesSpeedYAccTable               0xC270
#define wEntitiesSpeedZAccTable               0xC330
#define wEntitiesPosXAccTable                 0xC260  /* Alias for SpeedXAccTable */
#define wEntitiesPosYAccTable                 0xC270  /* Alias for SpeedYAccTable */
#define wEntitiesPosZAccTable                 0xC330  /* Alias for SpeedZAccTable */
#define wEntitiesPosZSignTable                0xC340  /* Reuses PhysicsFlagsTable space */
#define wEntitiesTransitionCountdownTable     0xC2E0
#define wEntitiesPrivateCountdown1Table       0xC2F0
#define wEntitiesIgnoreHitsCountdownTable     0xC410
#define wEntitiesSlowTransitionCountdownTable 0xC450
#define wEntitiesPrivateCountdown3Table       0xC480
#define wEntitiesStateTable                   0xC290
#define wEntitiesHitboxFlagsTable             0xC350
#define wEntitiesSpriteVariantTable           0xC3B0
#define wEntitiesTransitionCountdownTable     0xC2E0
#define wEntitiesPrivateCountdown1Table       0xC2F0
#define wEntitiesIgnoreHitsCountdownTable     0xC410
#define wEntitiesSlowTransitionCountdownTable 0xC450
#define wEntitiesPrivateCountdown3Table       0xC480
#define wEntitiesStateTable                   0xC290
#define wEntitiesHitboxFlagsTable             0xC350
#define wEntitiesSpriteVariantTable           0xC3B0
#define wEntitiesHitboxPositionTable          0xD580
#define wEntitiesCollisionsTable              0xC2A0
#define wEntitiesRecoilVelocityX              0xC3F0
#define wEntitiesRecoilVelocityY              0xC400
#define wEntitiesOptions1Table                0xC430
#define wEntitiesLoadOrderTable               0xC460
#define wEntitiesPowerRecoilingTable          0xC4A0
#define wEntitiesFallingTargetXTable          0xC4B0
#define wEntitiesFallingTargetYTable          0xC4C0
#define wEntitiesGroundStatusTable            0xC470
#define wEntitiesSpeedZTable                  0xC320
#define wEntitiesSpeedZAccTable               0xC330
#define wEntitiesFlashCountdownTable          0xC420
#define wEntitiesLiftedTable                  0xC490
#define wEntitiesClearedRooms                 0xCF00
#define wEntitiesRoomTable                    0xC3E0
#define wEntitiesHealthTable                  0xC360
#define wEntitiesHealthGroup                  0xC4D0
#define wEntitiesDroppedItemTable             0xC4E0
#define wEntitiesHitboxPositionTable          0xD580
#define wEnemyWasKilled                       0xC113
#define wInventoryAppearing                   0xC14F
#define wD46B                                 0xD46B
#define wC199                                 0xC199
#define wC16E                                 0xC16E
#define wLiftedEntityType                     0xC5A8
#define wPitSlippingCounter                   0xC1BB
#define wObjectAffectingBGPalette             0xC3CB
#define wBGPaletteEffectAddress               0xC3CC
#define wC3CD                                 0xC3CD
#define wOcarinaMenuOpen                      0xC1B5
#define wOcarinaMenuOpening                   0xC1B8
#define wOcarinaMenuClosing                   0xC1B9
#define wBossIntroDelay                       0xC165
#define wTransitionSequenceCounter           0xC16B
#define wDidBossIntro                         0xC1BD
#define wInBossBattle                         0xC1BE
#define wEntitiesStatusTable                  0xC280
#define wEntitiesTypeTable                    0xC3A0
#define wActiveEntityIndex                    0xC123
#define wC111                                 0xC111
#define wC1A7                                 0xC1A7
#define wC1A8                                 0xC1A8
#define wC3C1                                 0xC3C1
#define wBossAgonySFXCountdown                0xC5A7
#define wOAMNextAvailableSlot                 0xC3C0
#define wItemUsageContext                     0xC1AD
#define wSwordMoblinAlertingSoundCounter      0xC502
#define wEntityHorizontallyCollidedObject     0xC503
#define wPickedUpRockIndex                    0xC50C
#define wEntityVerticallyCollidedObject       0xC50D

/* WRAM Transient VFX Tables */
#define wTranscientVfxTypeTable      0xC510
#define wTranscientVfxCountdownTable 0xC520
#define wTranscientVfxPosXTable      0xC530
#define wTranscientVfxPosYTable      0xC540
#define wC5A6                        0xC5A6
#define wC5C0                        0xC5C0

/* HRAM Sections & Variables */
#define hGameValuesSection           0xFF90
#define hNeedsUpdatingBGTiles        0xFF90
#define hNeedsUpdatingEntityTilesA   0xFF91
#define hBGTilesLoadingStage         0xFF92
#define hWorldTileset                0xFF94
#define W_TILESET_KEEP               0x0F
#define W_TILESET_NO_UPDATE          0xFF
#define hBaseScrollX                 0xFF96
#define hBaseScrollY                 0xFF97
#define hLinkPositionX               0xFF98
#define hLinkPositionY               0xFF99
#define hLinkPhysicsModifier         0xFF9C
#define hLinkFinalPositionX          0xFF9F
#define hLinkFinalPositionY          0xFFA0
#define hAnimatedTilesGroup          0xFFA4
#define hMusicFadeOutTimer           0xFFA8
#define hMusicFadeInTimer            0xFFAB
#define hDefaultMusicTrack           0xFFB0
#define hNextMusicTrackToFadeInto    0xFFB1
#define hContinueMusicAfterWarp      0xFFBC
#define hNextDefaultMusicTrack       0xFFBF
#define hPressedButtonsMask          0xFFCB
#define hJoypadState                 0xFFCC
#define hIntersectedObjectTop        0xFFCD
#define hIntersectedObjectLeft       0xFFCE
#define hIntersectedObjectBGAddressHigh 0xFFCF
#define hIntersectedObjectBGAddressLow  0xFFD0
#define hInterrupts                  0xFFD2
#define hMultiPurpose0               0xFFD7
#define hMultiPurpose1               0xFFD8
#define hMultiPurpose2               0xFFD9
#define hMultiPurpose3               0xFFDA
#define hMultiPurpose8               0xFFDF
#define hMultiPurpose9               0xFFE0
#define hMultiPurposeA               0xFFE1
#define hMultiPurposeB               0xFFE2
#define hMultiPurposeC               0xFFE3
#define hMultiPurposeD               0xFFE4
#define hMultiPurposeF               0xFFE6
#define hFreeWarpDataAddress         0xFFE6
#define hStaircase                   0xFFAC
#define hStaircasePosX               0xFFAD
#define hStaircasePosY               0xFFAE
#define hFrameCounter                0xFFE7
#define hMultiPurposeG               0xFFE8
#define hRoomBank                    0xFFE8
#define hMultiPurposeH               0xFFE9
#define hIndexOfObjectBelowLink      0xFFE9
#define hSwitchBlockNeedingUpdate    0xFFBB
#define hActiveEntityStatus                   0xFFEA
#define hActiveEntityType                     0xFFEB
#define hActiveEntityVisualPosY               0xFFEC
#define hActiveEntityFlipAttribute            0xFFED
#define hActiveEntityPosX                     0xFFEE
#define hActiveEntityPosY                     0xFFEF
#define hActiveEntityState                    0xFFF0
#define hActiveEntitySpriteVariant            0xFFF1
#define hActiveEntityTilesOffset              0xFFF5
#define hLinkSlowWalkingSpeed                 0xFFB2
#define hDialogBackgroundTile                 0xFFE8
#define hDefaultMusicTrackAlt                 0xFFBD
#define hActiveEntityNoBGCollision            0xFFBE
#define hJingle                      0xFFF2
#define hWaveSfx                     0xFFF3
#define hNoiseSfx                    0xFFF4
#define hMapRoom                     0xFFF6
#define hMapId                       0xFFF7
#define hRoomStatus                  0xFFF8
#define hIsSideScrolling             0xFFF9
#define hIsComputingFrame            0xFFFD
#define hIsGBC                       0xFFFE

/* Map ID Constants */
#define MAP_EAGLES_TOWER             0x06
#define MAP_CAVE_B                   0x0A
#define MAP_HOUSE                    0x10
#define MAP_KANALET                  0x14
#define MAP_COLOR_DUNGEON            0xFF

/* Room Constants */
#define ROOM_INDOOR_B_FISHING_MINIGAME 0xB1
#define ROOM_INDOOR_B_CAMERA_SHOP      0xB5
#define ROOM_INDOOR_B_SEASHELL_MANSION 0xE9
#define ROOM_INDOOR_B_MANBO            0xFD
#define UNKNOWN_ROOM_12                0x12


#define wIsGelClingingToLink            0xC117
#define wSwordAnimationState            0xC137
#define wC138                           0xC138
#define wIsLinkPushing                  0xC144
#define wIsLinkInTheAir                 0xC146
#define wActiveProjectileCount          0xC14D
#define wHasPlacedBomb                  0xC14E
#define wHasMirrorShield                0xC15A
#define wIsUsingShield                  0xC15B
#define wIsCarryingLiftedObject         0xC15C
#define wC160                           0xC160
#define wNextJingle                     0xC169
#define wC16A                           0xC16A
#define wLinkAttackStepAnimationCountdown 0xC19B
#define wIsUsingHookshot                0xC1A4
#define wC1AC                           0xC1AC
#define wLinkUsingShovel                0xC1C7
#define wLinkUsingShovelTimer           0xC1C8
#define wBlockItemUsage                 0xC50A
#define wSwordCollisionEnabled          0xC5B0
#define wInventoryItems_BButtonSlot     0xDB00
#define wInventoryBButtonSlot           0xDB00
#define wInventoryItems_AButtonSlot     0xDB01
#define wInventoryAButtonSlot           0xDB01
#define wSeashellsCount                 0xDB0F
#define wShieldLevel                    0xDB44
#define wBombCount                      0xDB4D
#define hLinkInteractiveMotionBlocked   0xFFA1
#define wC130                       0xC130
#define wIsShootingArrow            0xC14C
#define wC152                       0xC152
#define wC153                       0xC153
#define wC158                       0xC158
#define wC16D                       0xC16D
#define wDialogGotItem              0xC1A9
#define wDialogGotItemCountdown     0xC1AA
#define wBombArrowCooldown          0xC1C0
#define wLatestDroppedBombEntityIndex 0xC1C1
#define wLatestShotArrowEntityIndex 0xC1C2
#define wEntitiesDirectionTable     0xC380
#define wEntitiesUnknowTableJ       0xC4F0
#define wFullHearts                 0xC5A9
#define wEntitiesThrownDirectionTable 0xC5D0
#define wActivePowerUp              0xD47C
#define wArrowCount                 0xDB45
#define wHasToadstool               0xDB4B
#define wMagicPowderCount           0xDB4C
#define wSwordLevel                 0xDB4E
#define wRupeeCountHigh             0xDB5D
#define wRupeeCountLow              0xDB5E
#define wConsecutiveStepsCount      0xC120
#define wSwordDirection             0xC136
#define wLinkObjectPhysics          0xC181
#define wC1C4                       0xC1C4
#define wC1C9                       0xC1C9
#define wC1CA                       0xC1CA
#define wEntitiesSpeedZTable        0xC320
#define wC139                           0xC139
#define wC13A                           0xC13A
#define wC13B                           0xC13B
#define wC145                           0xC145
#define wScreenShakeCountdown           0xC157
#define wTransitionGfx                  0xC17F
#define wTransitionGfxFrameCount        0xC180
#define wC3C9                           0xC3C9
#define wItemPickedUpInShop             0xC509
#define wD463                           0xD463
#define wDungeonMinimap                 0xD480
#define wDidStealItem                   0xD47E
#define wSwitchableObjectAnimationStage 0xD6F8
#define wLinkStandingOnSwitchBlock      0xD6F9
#define wSwitchBlocksState              0xD6FB
#define wSpawnLocationData              0xDB5F
#define wHasInstrument7                 0xDB6B
#define wEggMazeProgress                0xC5AA
#define wWindFishEggMazeSequenceOffset  0xDB7C
#define wMapEntranceRoom                0xDB9C
#define wMapEntrancePositionX           0xDB9D
#define wMapEntrancePositionY           0xDB9E
#define wIndoorRoom                     0xDBAE
#define wPhotos1                        0xDC0C
#define wBGPaletteTransitionEffect      0xDDD6
#define wDDD7                           0xDDD7
#define wLinkOAMBuffer                  0xC000
#define wC11D                           0xC11D
#define wC11E                           0xC11E
#define wC135                           0xC135
#define wC13C                           0xC13C
#define wCreditsScratch0                0xD000
#define wIsFileSelectionArrowShifted    0xD000
#define wIntroLightningVisibleCountdown       0xD000
#define wScrollXOffsetForSection              0xC100
#define wC17E                                 0xC17E
#define wIntroBGYOffset                       0xC106
#define wD003                                 0xD003
#define wD004                                 0xD004
#define wD005                                 0xD005
#define wD205                                 0xD205
#define wD5C0                                 0xD5C0
#define wD5C1                                 0xD5C1
#define wD5C2                                 0xD5C2
#define wD5C3                                 0xD5C3
#define wD5C4                                 0xD5C4
#define wC144                                 0xC144
#define wD00A                                 0xD00A
#define wD00B                                 0xD00B
#define wD00C                                 0xD00C
#define wD00D                                 0xD00D
#define wCreditsSubscene                      0xD00E
#define wD010                                 0xD010
#define wD011                                 0xD011
#define wD012                                 0xD012
#define wD014                                 0xD014
#define wD015                                 0xD015
#define wD018                                 0xD018
#define wObjPal1                              0xDC50
#define wObjPal6                              0xDC78
#define wObjPal8                              0xDC88
#define wPalettePartialCopyColorIndexStart    0xDDD3
#define wPalettePartialCopyColorCount         0xDDD4
#define wD00F                                 0xD00F
#define wD013                                 0xD013
#define wD016                                 0xD016
#define wD017                                 0xD017
#define wD153                                 0xD153
#define wIntroTimer                     0xD001
#define wIntroSubTimer                  0xD002
#define wD006                           0xD006
#define wD007                           0xD007
#define wD008                           0xD008
#define wD009                           0xD009
#define wWindowY                        0xDB9A
#define wInvincibilityCounter           0xDBC7
#define wTunicType                      0xDC0F
#define wPullCounter                    0xC15F
#define wMazeSignpostPos                0xD473
#define wC15D                           0xC15D
#define wAttackDamageType               0xC19E
#define wC149                           0xC149
#define wC11A                           0xC11A
#define wC11B                           0xC11B
#define wOcarinaSongFlags               0xDB49
#define wRoomEvent                      0xC18E
#define wInventoryItems                 0xDB00
#define wHasFlippers                    0xDB0C
#define wBGUpdateRegionOriginLow        0xC127
#define wBGUpdateRegionOriginHigh       0xC126
#define wBGUpdateRegionTilesCount       0xC128
#define wRoomTransitionFramesBeforeMidScreen 0xC129
#define wTransitionOffset               0xC12A
#define wTransitionZeroNeverUsed        0xC12B
#define wRoomTransitionTargetScrollX    0xC12C
#define wRoomTransitionTargetScrollY    0xC12D
#define wBGOriginHigh                   0xC12E
#define wBGOriginLow                    0xC12F
#define wHasTailKey                     0xDB11
#define wHasAnglerKey                   0xDB12
#define wHasFaceKey                     0xDB13
#define wHasBirdKey                     0xDB14
#define wGoldenLeavesCount              0xDB15
#define wWreckingBallRoom                       0xDB6F
#define wWreckingBallPosX                       0xDB70
#define wWreckingBallPosY                       0xDB71
#define wEntitiesLoadOrderTable                 0xC460
#define wEntitiesClearedRooms                   0xCF00
#define wRecentRoomsIndex                       0xCE80
#define wRecentRooms                            0xCE81
#define wDungeonItemFlags                       0xDB16
#define wLinkFallingDownObjectPhysics           0xDBCB
#define wCurrentDungeonItemFlags                0xDBCC
#define wColorDungeonItemFlags                  0xDDDA
#define wLinkPositionXHistory                   0xD155
#define wLinkPositionYHistory                   0xD175
#define wLinkPositionZHistory                   0xD195
#define wLinkDirectionHistory                   0xD1B5
#define wLinkSpeedY                             0xFF9B
#define wLinkSpeedX                             0xFF9A
#define wLinkVelocityZ                          0xFFA3
#define wLinkCountdown                          0xFFB7
#define wLinkPositionZ                          0xFFA2
#define wEntitiesPrivateState4Table             0xC440
#define wEntitiesPrivateState5Table             0xC390
#define wEntitiesPrivateCountdown2Table         0xC300
#define wC13B                                   0xC13B
#define wC167                                   0xC167
#define wDB10                                   0xDB10
#define wFreeMovementMode                       0xC17B
#define wPegasusBootsCollisionCountdown         0xC178
#define wPegasusBootsCollisionPosX              0xC179
#define wPegasusBootsCollisionPosY              0xC17A
#define wTextDebuggerDialogId                   0xC109
#define wEntitiesPrivateState1Table             0xC2B0
#define wEntitiesPrivateState2Table             0xC2C0
#define wEntitiesPrivateState3Table             0xC2D0
#define wHasInstrument4                         0xDB68
#define wPowerBraceletLevel                     0xDB43
#define wOBJ0Palette                            0xDB98
#define wOBJ1Palette                            0xDB99
#define hButtonsInactiveDelay                   0xFFB5
#define hLinkPunchedAwayCountdown               0xFFB6
#define wBGPalette                              0xDB97
#define hDMARoutine                             0xFFC0
#define wDB54                                 0xDB54
#define wC13F                                 0xC13F
#define wBGMapToLoad                          0xD6FF
#define wPaletteUnknownE                      0xDDD5
#define wD210                                 0xD210
#define wSubscreenScrollIncrement             0xC150
#define wInventoryShouldScroll                0xC151
#define wC154                                 0xC154
#define wTilesetToLoad                        0xD6FE
#define wScreenShakeHorizontal                0xC155
#define wScreenShakeVertical                  0xC156
#define wD211                                 0xD211
#define wD212                                 0xD212
#define wD213                                 0xD213
#define wD214                                 0xD214
#define wD215                                 0xD215
#define wFinalNightmareForm                   0xD219
#define wC116                                 0xC116
#define wScrollXOffset                        0xC1BF
#define wBGPal1                               0xDC10
#define hVolumeRight                          0xFFA9
#define hVolumeLeft                           0xFFAA
#define wDBB4                                 0xDBB4
#define wC1B1                                 0xC1B1
#define wC1B2                                 0xC1B2
#define wC1B3                                 0xC1B3
#define wC1B4                                 0xC1B4
#define wC5A2                                 0xC5A2
#define wLCDControl                           0xD6FD
#define wC182                                 0xC182
#define wC1B0                                 0xC1B0
#define wWarp0Map                             0xD402
#define wWarp0Room                            0xD403
#define wWarp0DestinationX                    0xD404
#define wWarp0DestinationY                    0xD405
#define hMultiPurpose4                        0xFFDB
#define wHealth                               0xDB5A
#define wMaxHearts                            0xDB5B
#define wPhotos1                              0xDC0C
#define wPhotos2                              0xDC0D
#define wDrawCommandsSize                     0xD600
#define wSaveSlotNames                        0xDB80
#define wSaveSlot                             0xDBA6
#define wSaveFilesCount                       0xDBA7
#define wDBD1                                  0xDBD1
#define wAddHealthBuffer                       0xDB93
#define wSubtractHealthBuffer                  0xDB94
#define wAddRupeeBufferLow                     0xDB90
#define wAddRupeeBufferHigh                    0xDB8F
#define wSubstractRupeeBufferLow               0xDB92
#define wSubstractRupeeBufferHigh              0xDB91
#define wSpawnPositionX                        0xDB62
#define wSpawnPositionY                        0xDB63
#define wSpawnMapRoom                          0xDB61
#define wSpawnMapId                            0xDB60
#define wSpawnIndoorRoom                       0xDB64
#define wSpawnIsIndoor                         0xDB5F
#define wMaxArrows                             0xDB78
#define wMaxBombs                              0xDB77
#define wMaxMagicPowder                        0xDB76
#define wDBA8                                  0xDBA8
#define wNameEntryCurrentChar                  0xDBA9
#define wSaveSlotNameCharIndex                 0xDBAA
#define wSaveSlot1Name                         0xDB80
#define wSaveSlot2Name                         0xDB85
#define wSaveSlot3Name                         0xDB8A
#define wFile1DeathCountHigh                   0xDC00
#define wFile1DeathCountLow                    0xDC01
#define wFile2DeathCountHigh                   0xDC02
#define wFile2DeathCountLow                    0xDC03
#define wFile3DeathCountHigh                   0xDC04
#define wFile3DeathCountLow                    0xDC05
#define wFile1Health                           0xDC06
#define wFile2Health                           0xDC07
#define wFile3Health                           0xDC08
#define wFile1MaxHearts                        0xDC09
#define wFile2MaxHearts                        0xDC0A
#define wFile3MaxHearts                        0xDC0B
#define wForceFileSelectionScreenMusic         0xD47B
#define wDeathCount                           0xDB57
#define hGameOverStage                        0xFF9C
#define hLinkCountdown                        0xFFB7
#define wPieceOfPowerKillCount                0xD415
#define wActivePowerUp                        0xD47C
#define wPowerUpHits                          0xD47A
#define wD475                                 0xD475
#define wObjectAffectingBGPalette             0xC3CB
#define wBGPaletteEffectAddress               0xC3CC
#define wC3CD                                 0xC3CD
#define wDBD1                                 0xDBD1
#define wInvincibilityCounter                 0xDBC7
#define hActiveEntityTilesOffset              0xFFF5
#define wMinimapLayout                        0xDBB0
#define wMinimapTilemap                       0xD651
#define wCompassSfxCountdown                  0xD462
#define wD463                                 0xD463
#define wC16C                                 0xC16C
#define wC5AD                                 0xC5AD
#define wTransitionSequenceCounter            0xC16B
#define wNextWorldMusicTrackCountdown         0xC5AF
#define wSwitchableObjectAnimationStage       0xD6F8
#define wIsFileSelectionArrowShifted          0xD000
#define hNeedsUpdatingBGTiles                 0xFF90
#define hNeedsUpdatingEntityTilesA            0xFF91
#define hWorldTileset                         0xFF94
#define hTileGlintSequence                    0xFFB9
#define wDBAC                                 0xDBAC
#define wHasDungeonMap                        0xDBCC
#define wHasDungeonCompass                    0xDBCD
#define wHasDungeonStoneBeak                  0xDBCE
#define wHasDungeonBossKey                    0xDBCF
#define wSmallKeysCount                       0xDBD0
#define wLinkMapEntryPositionX                0xDBB1
#define wLinkMapEntryPositionY                0xDBB2
#define wMapEntrancePositionZ                 0xDBC8
#define wSwitchButtonPressed                 0xC1CB
#define wHasInstrument1                       0xDB65
#define wHasInstrument2                       0xDB66
#define wHasInstrument3                       0xDB67
#define wHasInstrument5                       0xDB69
#define wHasInstrument6                       0xDB6A
#define wHasInstrument8                       0xDB6C
#define wC3C4                                 0xC3C4
#define wC3C5                                 0xC3C5
#define wC3C7                                 0xC3C7
#define wPhotoAlbumCooldown                   0xDE05
#define wDebugWarpIndex                       0xD479
#define wColorDungonCorrectTombStones         0xDDD9
#define wD466                                 0xD466
#define wNoiseSfxSeaWavesCounter              0xC114
#define wC550                                 0xC550
#define wC560                                 0xC560
#define wC570                                 0xC570
#define wC590                                 0xC590
#define wD200                                 0xD200
#define wC166                                 0xC166
#define wLinkPlayingOcarinaCountdown          0xC166
#define wC1CF                                 0xC1CF
#define wC5A3                                 0xC5A3
#define wC5A3                                 0xC5A3
#define wC5A4                                 0xC5A4
#define wC5A5                                 0xC5A5
#define wD461                                 0xD461
#define wD465                                 0xD465
#define wD461                                 0xD461
#define wD465                                 0xD465
#define wBossDefeated                         0xD46C
#define wSelectedSongIndex                    0xDB4A
#define wC10A                                 0xC10A
#define wCollisionType                        0xC133
#define wIgnoreLinkCollisionsCountdown        0xC13E
#define wLinkGroundStatus                     0xC11F
#define wInventoryAppearing                   0xC14F
#define wIsLinkImmuneToCollisionDamage        0xC1C6
#define wGuardianAcornCounter                 0xD471

#endif /* LADX_CONSTANTS_MEMORY_H */
